# -*- coding: utf-8 -*-
"""Suger_DNN/LSTM_For_Trading_signals_documented.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zQNIlqjIQw33u19TPPqclsgRtFmDYtO

# Sugar DNN/LSTM for Trading Signals

This notebook builds and evaluates deep learning models (feed‑forward DNN and LSTM)
to generate trading signals on future contracts and commodities spot prices.

It is structured into the following main steps:

1. **Environment setup** – install and import required libraries and mount Google Drive.
2. **Data loading and cleaning** – read raw futures/spot Excel files and tidy them.
3. **Feature engineering & technical indicators** – compute rolling statistics, RSI, ATR, etc.
4. **Strategy & label generation** – simulate a trading strategy and create supervised learning labels.
5. **Model helpers** – utility functions for model building, custom losses and data sequencing.
6. **Hyper‑parameter tuning** – use Optuna to tune focal‑loss and model hyper‑parameters.
7. **Pre‑processing & train/validation split** – scale features and build DNN/LSTM inputs.
8. **Fine‑tuning & backtesting** – run Optuna studies and backtest the selected models.

Use the section titles below as a guide when navigating or re‑using parts of this notebook.

## 1. Environment setup and imports

Install additional Python packages (such as **Optuna**) and import the core
libraries used throughout the notebook:

- numerical computing: **NumPy**
- data manipulation: **pandas**
- plotting: **matplotlib**, **seaborn**
- general configuration: warning filters, etc.

We also mount Google Drive in order to load and save datasets and trained models.
"""

!pip install optuna

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import datetime as dt
from tensorflow import keras
from keras.metrics import Precision, Recall
from tensorflow.keras import regularizers
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report
from tensorflow.keras.models import load_model


from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras import backend as K
from scipy.stats import linregress
from plotly.subplots import make_subplots
import plotly.graph_objects as go

import time
import optuna
#import optuna
import os
from typing import Optional

from google.colab import drive
drive.mount('/content/drive')



"""## 2. General helper functions

This notebook defines several small utility functions (for plotting, scaling,
sequence creation, and generic processing) that are reused across later sections.

Keeping this logic in dedicated helpers makes the main modeling and backtesting
code easier to read and maintain.

## 3. Data loading and basic cleaning

Functions in this section perform the first stage of data preparation, including:

- cleaning the **SB11 futures** dataset and setting the date index
- cleaning the **VHP spot** dataset and fixing header rows
- handling missing values (with options for random noise and sigma‑based thresholds)
- merging futures and spot data and preparing them for feature engineering.
"""

def clean_SB11(df):


  df = df.set_index('Date')
  return df

def clean_spot(df):
  new_header = df.iloc[1]
  df = df.iloc[2:].copy()
  df.columns = new_header
  df.reset_index(drop=True, inplace=True)
  df.rename(columns={'DATE':'Date'}, inplace = True)
  #df = df[df['Date'] != 'DATE']  # Remove the bad row
  df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
  df = df.set_index('Date')
  df =handle_missing_values(df, sigma_window=30, seed=42)
  df['MID'] = (df['BID'] + df['OFFER']) / 2




  return df

def handle_missing_values(data: pd.DataFrame, sigma_window: int = 30, seed: Optional[int] = None) -> pd.DataFrame:
    if seed is not None:
        np.random.seed(seed)

    data_filled = data.copy()

    def _fill_series(mid_series: pd.Series) -> pd.Series:
        mid = pd.to_numeric(mid_series.copy(), errors='coerce')
        filled = mid.copy()
        is_missing = mid.isna().values
        n = len(mid)

        i = 0
        while i < n:
            if not is_missing[i]:
                i += 1
                continue

            start = i
            while i < n and is_missing[i]:
                i += 1
            end = i

            prev_idx = start - 1 if start > 0 else None
            next_idx = end if end < n else None

            A_val = mid.iloc[prev_idx] if prev_idx is not None else None
            B_val = mid.iloc[next_idx] if next_idx is not None else None

            if A_val is None and B_val is None:
                continue
            if A_val is None:
                A_val = B_val
            if B_val is None:
                B_val = A_val

            window_vals = []
            if prev_idx is not None:
                start_window = max(0, prev_idx - sigma_window + 1)
                window_vals.append(mid.iloc[start_window:prev_idx + 1])
            if next_idx is not None:
                end_window = min(n, next_idx + sigma_window)
                window_vals.append(mid.iloc[next_idx:end_window])

            window_vals = pd.concat(window_vals).dropna().sort_index()
            if len(window_vals) > 1:
                log_rets = np.log(window_vals / window_vals.shift(1)).dropna()
                sigma = log_rets.std()
            else:
                sigma = 0.0001

            num_missing = end - start
            logA, logB = np.log(A_val), np.log(B_val)
            increments = np.random.normal(0, sigma, size=num_missing + 1)
            X = np.concatenate([[0], np.cumsum(increments)])
            X_end = X[-1]
            t = np.linspace(0, 1, num_missing + 2)
            Y_log = logA + t * (logB - logA) + (X - t * X_end)
            filled_vals = np.exp(Y_log[1:-1])
            filled.iloc[start:end] = filled_vals

        return filled

    if isinstance(data_filled.columns, pd.MultiIndex):
        for key in data_filled.columns.get_level_values(0).unique():
            if ('BID' in data_filled[key]) and ('OFFER' in data_filled[key]):
                bid = pd.to_numeric(data_filled[key]['BID'], errors='coerce')
                offer = pd.to_numeric(data_filled[key]['OFFER'], errors='coerce')

                bid_filled = bid.fillna(offer)
                offer_filled = offer.fillna(bid)
                mid_series = 0.5 * (bid_filled + offer_filled)
                mid_filled = _fill_series(mid_series)

                missing_mask = bid.isna() & offer.isna()
                data_filled.loc[missing_mask, (key, 'BID')] = mid_filled[missing_mask].values
                data_filled.loc[missing_mask, (key, 'OFFER')] = mid_filled[missing_mask].values
                data_filled['BID'] = pd.to_numeric(data_filled['BID'], errors='coerce')
                data_filled['OFFER'] = pd.to_numeric(data_filled['OFFER'], errors='coerce')

                data_filled['BID'] = data_filled['BID'].fillna(data_filled['OFFER'])
                data_filled['OFFER'] = data_filled['OFFER'].fillna(data_filled['BID'])



    else:
        cols = list(data_filled.columns)
        if {'BID', 'OFFER'}.issubset(cols):
            bid = pd.to_numeric(data_filled['BID'], errors='coerce')
            offer = pd.to_numeric(data_filled['OFFER'], errors='coerce')

            bid_filled = bid.fillna(offer)
            offer_filled = offer.fillna(bid)
            mid_series = 0.5 * (bid_filled + offer_filled)
            mid_filled = _fill_series(mid_series)

            missing_mask = bid.isna() & offer.isna()
            data_filled.loc[missing_mask, 'BID'] = mid_filled[missing_mask].values
            data_filled.loc[missing_mask, 'OFFER'] = mid_filled[missing_mask].values
            data_filled['BID'] = data_filled['BID'].fillna(data_filled['OFFER'])
            data_filled['OFFER'] = data_filled['OFFER'].fillna(data_filled['BID'])

        else:
            series = data_filled.iloc[:, 0] if isinstance(data_filled, pd.DataFrame) else data_filled
            filled_series = _fill_series(series)
            if isinstance(data_filled, pd.DataFrame):
                data_filled.iloc[:, 0] = filled_series
            else:
                data_filled = filled_series

    return data_filled

def feat_ing(df1,df2,vol_window_fut,trend_fut,vol_window,trend_window,RSIwindow,Zscorewindow, window_slope, RSI_thresh_up, RSI_thresh_down, slope_thresh,order):
  df1=df1.copy()
  df2=df2.copy()

  Data = pd.merge(df1,df2['Close'],on ='Date',how = 'inner')

  Data['Close_shifted'] = Data['Close'].shift(1)

  Data['MID_shifted_1']= Data['MID'].shift(1)

  Data['MID_shifted_2']= Data['MID'].shift(2)

  Data['MID_shifted_3']= Data['MID'].shift(3)

  Data["Vol_fut"] = Data['Close_shifted'].rolling(vol_window_fut).std()

  Data["Trend_fut"] = Data['Close_shifted'].diff().rolling(trend_fut).mean()

  Data['Volatility'] = Data['MID'].rolling(vol_window).std()
  Data['Trend'] = Data['MID'].diff().rolling(trend_window).mean()

  Data['RSI'] = compute_rsi(Data['MID'],RSIwindow)

  Data['Zscore'] = compute_zscore(Data['MID'],Zscorewindow)
  mid_diff = Data['MID'].diff().abs()
  Data['ATR_mid'] =mid_diff.rolling(window=14).mean()

  Data['SMA_15'] = compute_sma(Data['MID'], window=15)
  Data['SMA_30'] = compute_sma(Data['MID'], window=30)

  Data['EMA_15'] = compute_ema(Data['MID'], span=15)
  Data['EMA_30'] = compute_ema(Data['MID'], span=30)

  Data['slopeMA15'] = Data['SMA_15'].rolling(window = 10).apply(get_slope, raw = True)
  Data['slopeMA30'] = Data['SMA_30'].rolling(window = 10).apply(get_slope, raw = True)

  # Compute RSI slope and regime
  if 'RSI' in Data.columns:
      Data['RSI_slope'] = calculate_slope_series(Data['RSI'], window_slope)
      Data['regime'] = np.where(
          (Data['RSI'] < RSI_thresh_down) & (Data['RSI_slope'] > slope_thresh), 'bullish',
          np.where((Data['RSI'] > RSI_thresh_up) & (Data['RSI_slope'] < -slope_thresh), 'bearish', 'neutral')
      )
  else:
      Data['regime'] = 'neutral'

  # Identify local minima and maxima for filtering
    # number of periods around the point to consider as extrema
  Data['is_local_min'] = False
  Data['is_local_max'] = False
  min_idxs = argrelextrema(Data['Close'].values, np.less_equal, order=order)[0]
  max_idxs = argrelextrema(Data['Close'].values, np.greater_equal, order=order)[0]
  Data.loc[Data.index[min_idxs], 'is_local_min'] = True
  Data.loc[Data.index[max_idxs], 'is_local_max'] = True





  Data.drop(['FUTURES','OFFER','BID'],axis = 1, inplace=True)
  Data.dropna(inplace = True)

  return Data

"""## 4. Technical indicators and rolling features

Here we construct the technical features that will later be used both for:
- trading rule generation, and
- as inputs to the deep learning models.

Indicators include:
- simple and exponential moving averages (SMA / EMA)
- rolling slopes of moving averages
- **RSI** and its slope
- volatility and trend measures
- ATR‑like measures and z‑scores.

"""

def compute_sma(series, window):
    return series.rolling(window=window).mean()

def compute_ema(series, span):
    return series.ewm(span=span, adjust=False).mean()

def get_slope(array):
  y = np.array(array)
  x = np.arange(len(y))
  slope,intercept,_,_,_ = linregress(x,y)
  return slope

def compute_rsi(series, period):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=period).mean()
    avg_loss = loss.rolling(window=period).mean()
    #avg_gain = gain.ewm(span=period, adjust=False).mean()
    #avg_loss = loss.ewm(span=period, adjust=False).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def compute_zscore(series, window):
    mean = series.rolling(window).mean()
    std = series.rolling(window).std()
    zscore = (series - mean) / std
    return zscore

def calculate_slope_series(series, window):
    slopes = [np.nan] * (window - 1)
    for i in range(window - 1, len(series)):
        y = series[i - window + 1 : i + 1]
        x = np.arange(window)
        slope, _, _, _, _ = linregress(x, y)
        slopes.append(slope)
    return pd.Series(slopes, index=series.index)

"""## 5. Dataset labelling (target construction)

This section explains how raw time‑series data is transformed into
supervised learning targets.

Key steps:
- compute forward returns over a future window
- classify each point into regimes such as BUY / HOLD / SELL
- optionally use custom distance metrics (e.g. Lorentzian distance with k‑NN)
  to derive robust labels.

The resulting labels will be used to train the DNN and LSTM models.

"""

def lorentzian_distance(a, b):
    a = np.array(a, dtype=float)
    b = np.array(b, dtype=float)
    return np.sum(np.log1p(np.abs(a - b)))



# === KNN Classification with Lorentzian Distance ===
def lorentzian_knn_predict(X, query_vector, k):
    distances = np.array([lorentzian_distance(row, query_vector) for row in X])
    knn_idx = distances.argsort()[:k]
    return knn_idx

from scipy.signal import argrelextrema

def generate_signals_enhanced_RSI(df, k, vote_thresh, weighted,window_slope, RSI_thresh_up, RSI_thresh_down, slope_thresh,order):

    signals = pd.Series('HOLD', index=df.index, dtype='object')
    vote_series = pd.Series(np.nan, index=df.index)



    # Extract necessary arrays
    X = df.drop(columns=[ 'regime',	'is_local_min',	'is_local_max',	'Close'], errors='ignore').values
    prices = df['Close'].values
    regimes = df['regime'].values
    rsi = df['RSI'].values
    rsi_slope = df['RSI_slope'].values

    for i in range(k, len(df)):
        query = X[i]
        X_train = X[:i]
        idxs = lorentzian_knn_predict(X_train, query, k)

        if len(idxs) == 0:
            continue

        votes = []
        dist_list = []

        for j in idxs:
            if j < window_slope or j >= len(rsi):
                continue

            r = rsi[j]
            s = rsi_slope[j]

            if r < RSI_thresh_down and s > slope_thresh:
                votes.append(1)
            elif r > RSI_thresh_up and s < -slope_thresh:
                votes.append(-1)
            else:
                votes.append(0)

            dist = np.linalg.norm(X_train[j] - query)
            dist_list.append(dist)

        if len(votes) == 0:
            continue

        if weighted:
            epsilon = 1e-5
            dist_array = np.array(dist_list)
            weights = 1 / (dist_array + epsilon)
            weights /= weights.sum() + 1e-10
            vote_score = np.dot(votes, weights)
        else:
            vote_score = sum(votes) / (len(votes) + 1e-10)

        vote_score = round(vote_score, 2)
        vote_series.iloc[i] = vote_score

        # Apply final signal filtering with local extrema condition

        if vote_score >= vote_thresh and df['is_local_min'].iloc[i]:
                signals.iloc[i] = 'BUY'
        elif vote_score <= -vote_thresh and df['is_local_max'].iloc[i]:
                signals.iloc[i] = 'SELL'


    return signals

# ----------------------------------
# Run Strategy
# ----------------------------------
def generate_signals(df,df2,vol_window_fut,trend_fut,vol_window,trend_window,RSIwindow,Zscorewindow, k, vote_thresh, weighted,
                               window_slope, RSI_thresh_up, RSI_thresh_down, slope_thresh,order):
    df_strategy = df.copy()
    df_strategy = feat_ing(df_strategy,df2,vol_window_fut,trend_fut,vol_window,trend_window,RSIwindow,Zscorewindow,window_slope, RSI_thresh_up, RSI_thresh_down, slope_thresh,order)
    signals= generate_signals_enhanced_RSI(df_strategy, k, vote_thresh, weighted,
                                   window_slope, RSI_thresh_up, RSI_thresh_down, slope_thresh,order)
    df_strategy['signal'] = signals
    return df_strategy

"""## 6. Strategy definition and signal filters

Functions in this block implement the **trading strategy logic**:

- generate raw BUY / SELL / HOLD signals using enhanced RSI‑based rules
  (including RSI slope and regime information)
- apply additional filters such as local extrema and minimum distance between trades
- simulate the strategy over time and compute the resulting equity curve
- compare the strategy performance against a simple buy‑and‑hold benchmark.

"""

def compute_buy_and_hold(df, price_col='Close', initial_cash=1000):
    start_price = df[price_col].iloc[0]
    return df[price_col] / start_price * initial_cash

def filter_signals(series, trad_num):
    series = series.copy()
    last_trade = 'HOLD'
    trade_count = 0

    for i in range(len(series)):
        current = series[i]

        if current == 'HOLD':
            continue

        if current == last_trade:
            trade_count += 1
            if trade_count > trad_num:
                series[i] = 'HOLD'
        else:
            # Signal changed direction → reset
            last_trade = current
            trade_count = 1

    return series

def simulate_strategy_with_borrow_and_evolution(df,signal_col='signal', price_col='Close', initial_investment=100000):
    df = df.copy()
    df[signal_col] = df[signal_col].astype(str).str.strip().str.upper()

    cash = initial_investment
    portfolio = 0
    count_long = 0
    count_short = 0
    borrow = 0
    position = None
    entry_price = None

    results = []

    for i in range(len(df)):
        date = df.index[i]
        price = df.iloc[i][price_col]
        signal = df.iloc[i][signal_col]

        # Update the portfolio to reflect market movement before acting on new signal
        if position == 'LONG':
            portfolio = portfolio * (price / entry_price)
            entry_price = price  # reset entry to current for relative growth
        elif position == 'SHORT':
            portfolio = portfolio * (price / entry_price)
            entry_price = price

        # === Handle BUY signal ===
        if signal == 'BUY':
            if position == 'SHORT':
                # Close short: portfolio is negative
                cash += portfolio
                portfolio = 0
                position = None
                entry_price = None

            invest_amount = initial_investment


            if count_long == 0:
                final_coef = 1  # full exposure
            else:
                n = 2 + count_long  # prevents log(1)
                final_coef = np.log(n / (n - 1)) *0.5



            adjusted_investment = invest_amount * final_coef

            if cash < adjusted_investment:
                needed = adjusted_investment - cash
                borrow += needed
                cash += needed

            cash -= adjusted_investment
            portfolio += adjusted_investment
            position = 'LONG'
            count_long += 1
            count_short = 0
            entry_price = price

        # === Handle SELL signal ===
        elif signal == 'SELL':
            if position == 'LONG':
                # Close long
                cash += portfolio
                portfolio = 0
                position = None
                entry_price = None

                # Repay borrow
                if borrow > 0:
                    repayment = min(cash, borrow)
                    cash -= repayment
                    borrow -= repayment

            invest_amount = initial_investment


            if count_short == 0:
                final_coef = 1  # full exposure
            else:
                n = 2 + count_short  # prevents log(1)
                final_coef = np.log(n / (n - 1))*0.5



            adjusted_investment = invest_amount * final_coef

            cash += adjusted_investment
            portfolio -= adjusted_investment
            position = 'SHORT'
            count_short +=1
            count_long = 0
            entry_price = price

        total_equity = cash + portfolio - borrow

        results.append({
            'date': date,
            'signal': signal,
            'cash': round(cash, 2),
            'portfolio_value': round(portfolio, 2),
            'borrow': round(borrow, 2),
            'total_equity': round(total_equity, 2),
        })

    return pd.DataFrame(results).set_index('date')

"""## 7. Plotting helpers

Helper routines to visualise:

- price series with BUY / SELL markers
- equity curves for the strategy vs. buy‑and‑hold
- model predictions and realised PnL over time.

These functions make it easier to inspect and debug the behaviour of both
the rule‑based strategy and the learned models.

"""

def plot_interactive_signals_and_equity(Siganls_DataFrame, strategy_DataFrame, Benchmark, risk_free=0.04,
                                        price_col='Close', signal_col='signal',
                                        equity_col='total_equity',
                                        title_signals='Trading Signals with Vote Scores',
                                        title_equity='Strategy vs Benchmark'):

        returns = strategy_DataFrame[equity_col].pct_change().dropna()
        equity = strategy_DataFrame[equity_col]

    # Metrics
        total_profit = (equity.iloc[-1] - equity.iloc[0])/equity.iloc[0]
        max_running = equity.cummax()
        max_drawdown = (equity / max_running - 1).min()
        excess_returns  = returns - risk_free

        if returns.std() > 0:
          sharpe_ratio = ((returns.mean() * 252) - risk_free) / (returns.std() * np.sqrt(252))
        else:
          sharpe_ratio = np.nan
        #sharpe_ratio = ((returns.mean() - risk_free) /( returns.std()) )* np.sqrt(252) if returns.std() > 0 else 0

        metrics_text = f"<b>Total Profit:</b> {total_profit:,.2%} &nbsp;&nbsp;&nbsp;" \
                   f"<b>Max Drawdown:</b> {max_drawdown:.2%} &nbsp;&nbsp;&nbsp;" \
                   f"<b>Sharpe Ratio:</b> {sharpe_ratio:.2f}"

    # Subplot layout
        fig = make_subplots(rows=2, cols=1, shared_xaxes=True,
                        vertical_spacing=0.1,
                        row_heights=[0.6, 0.4],
                        subplot_titles=( title_signals, title_equity))

    # --- Signal Plot
        fig.add_trace(go.Scatter(
        x=Siganls_DataFrame.index,
        y=Siganls_DataFrame[price_col],
        name='Price',
        mode='lines',
        line=dict(color='black')
    ), row=1, col=1)

        buy_mask = Siganls_DataFrame[signal_col] == 'BUY'
        sell_mask = Siganls_DataFrame[signal_col] == 'SELL'

        fig.add_trace(go.Scatter(
        x=Siganls_DataFrame.index[buy_mask],
        y=Siganls_DataFrame[price_col][buy_mask],
        mode='markers',
        name='BUY',
        marker=dict(color='green', symbol='triangle-up', size=10)
    ), row=1, col=1)

        fig.add_trace(go.Scatter(
        x=Siganls_DataFrame.index[sell_mask],
        y=Siganls_DataFrame[price_col][sell_mask],
        mode='markers',
        name='SELL',
        marker=dict(color='red', symbol='triangle-down', size=10)
    ), row=1, col=1)

    # --- Equity Plot
        fig.add_trace(go.Scatter(
        x=strategy_DataFrame.index,
        y=strategy_DataFrame[equity_col],
        name='Strategy Equity',
        line=dict(color='blue')
    ), row=2, col=1)

        if Benchmark is not None:
            fig.add_trace(go.Scatter(
            x=Benchmark.index,
            y=Benchmark.values,
            name='Benchmark',
            line=dict(color='gray', dash='dot')
        ), row=2, col=1)

    # Layout
        fig.update_layout(
    height=700,
    width=1300,
    template='seaborn',
    hovermode='x unified',
    title="Trading Signals on NY SB11 Future Close & Strategy vs Benchmark",
    title_x=0.5,  # center the title
    showlegend=True,
    margin=dict(t=100, b=100),  # allow space at top and bottom
    annotations=[
        dict(
            x=0.5,
            y=-0.2,  # BELOW the chart
            xref='paper',
            yref='paper',
            text=metrics_text,
            showarrow=False,
            font=dict(size=14),
            align='center'
        )
    ]
)


        fig.show()

def plot_models_results(df, start, end,nums):

    pos = df.index.get_loc(start)

    df = df.copy().iloc[pos-window_size+1:]
    df = df.dropna(subset=features + ['signal'])

    test_X = df[features]
    test_y = df["signal"].values
    X_test_, y_test,_ = create_lstm_sequences(test_X, test_y, window_size)


    for e in nums:
        model = create_model(e)

        y_pred_probs = model.predict(X_test_)
        y_pred = np.argmax(y_pred_probs, axis=1)
        signals = np.array([decode_with_threshold(p, tau=0.40) for p in y_pred_probs])
        decoded_test = decode_signals(y_pred)

        test_idx = test_X.index[-len(decoded_test):]
        test_df = pd.DataFrame({'signal': decoded_test}, index=test_idx)
        test_slice = new_Data.loc[test_idx].drop(columns="signal", errors="ignore")
        merged = pd.concat([test_slice, test_df], axis=1)
        merged = merged.drop(columns=['Close'], errors='ignore')
        merged["signal"] = filter_signals(merged["signal"], trad_num=1)
        Data = pd.merge(merged, Futures_spot_price[['Close']], on='Date', how='inner')
        perf_test = simulate_strategy_with_borrow_and_evolution(
          Data, signal_col="signal", price_col="Close")
        benchmark = compute_buy_and_hold(Data.tail(len(perf_test['total_equity'])), initial_cash=100000)


        print(f"📊 Model {e}")
        plot_interactive_signals_and_equity(Data, perf_test, benchmark)

"""## 8. Deep learning helper functions

Here we gather all AI‑related helpers, including:

- creation of supervised sequences for **DNN** and **LSTM** models
- construction and compilation of Keras models
- definition of a **focal‑loss** variant to handle class imbalance
- utilities to load pre‑trained models from disk.

These building blocks are reused during hyper‑parameter tuning, training,
fine‑tuning and backtesting.

"""

def focal_loss(gamma, alpha):
    """
    Focal loss for multi-class classification
    :param gamma: focusing parameter
    :param alpha: weight for each class (list or numpy array of shape [num_classes])
    :return: focal loss function
    """
    def focal_loss_fixed(y_true, y_pred):
        # Clip the prediction values to avoid log(0) error
        epsilon = K.epsilon()
        y_pred = K.clip(y_pred, epsilon, 1. - epsilon)

        # Calculate cross entropy
        cross_entropy = -y_true * K.log(y_pred)

        # Calculate focal loss
        if alpha is not None:
            alpha_tensor = tf.convert_to_tensor(alpha, dtype=tf.float32)
            cross_entropy = alpha_tensor * cross_entropy

        loss = K.pow(1 - y_pred, gamma) * cross_entropy

        return K.sum(loss, axis=1)  # sum over classes

    return focal_loss_fixed

def create_train_val_lstm_sequences(X, y, window_size,size):

      tindex = int(size * len(X))

      train_data = X[:tindex]
      train_target = y[:tindex]
      X_seq_train = []
      y_seq_train = []

      for i in range(window_size, len(X)):
          X_seq_train.append(X[i - window_size:i])
          y_seq_train.append(y[i])  # the label at the end of the sequence

      test_data = X[tindex - window_size:]
      X_seq_test = []
      y_seq_test = y[tindex:]
      for i in range(window_size, len(test_data)):
          X_seq_test.append(test_data[i - window_size:i])


      return np.array(X_seq_train), np.array(y_seq_train),np.array(X_seq_test), np.array(y_seq_test)

def create_lstm_sequences(X, y, window_size):

      X_seq_test = []
      y_seq_test = []
      index = []

      for i in range(window_size, len(X)+1):
          X_seq_test.append(X[i - window_size:i])
          pos = X.index.get_indexer([X.index[i - window_size]])[0]  # note the list [...]
          index.append(pos)
          y_seq_test.append(y[i-1])
      return np.array(X_seq_test),np.array(y_seq_test),index

def rolling_standard_scaling(df, features, window):
    """
    Applies rolling z-score normalization (mean-std) over a specified window.

    Args:
        df (pd.DataFrame): Feature dataframe
        y (array-like): Corresponding labels (target values)
        features (list): List of column names to scale
        window (int): Rolling window size

    Returns:
        X (pd.DataFrame): Scaled features with original index (after dropna)
        y (np.array): Aligned labels
    """
    df = df.copy()
      # temporarily store target

    for col in features:
        df[col] = (df[col] - df[col].rolling(window=window, min_periods=window).mean()) / \
                  df[col].rolling(window=window, min_periods=window).std()

    df.dropna(inplace=True)

    X = df[features]
    y =df['signal']
    return X, y

def droping_non_num(df):
  df = df.drop(['regime',	'is_local_min'	,'is_local_max'],axis = 1)
  df.dropna(inplace = True)

  mapping = {'BUY':1,'HOLD':0,'SELL':2}
  df['signal'] = df['signal'].map(mapping)
  return df

def decode_signals(y_pred_numeric):
    reverse_mapping = {1: 'BUY', 0: 'HOLD', 2: 'SELL'}
    return [reverse_mapping[int(pred)] for pred in y_pred_numeric]

def decode_with_threshold(proba_vec, tau):
    """
    Decodes a probability vector into a trading signal using a confidence threshold.

    Args:
        proba_vec (array-like): [p_hold, p_buy, p_sell]
        tau (float): threshold value (e.g., 0.6)

    Returns:
        int: 0 for HOLD, 1 for BUY, 2 for SELL
    """
    p_hold, p_buy, p_sell = proba_vec

    if p_sell >= tau and p_buy >= tau:
        return 0  # SELL and p_sell == max(proba_vec)

    elif p_buy >= tau :
        return 1  # BUY and p_buy == max(proba_vec)

    elif p_sell >= tau :
        return 2  # SELL and p_sell == max(proba_vec)


    elif p_hold >= tau :
        return 0  # HOLD and p_hold == max(proba_vec)
    else:
        return 0 # fallback: take the highest prob regardless of tau

def build_model_LSTM(input_shape,lstm_size,lstm_size_2,dense_size, gamma, alpha):
    model = keras.models.Sequential()
    model.add(keras.layers.LSTM(lstm_size, return_sequences=True, input_shape=(input_shape)))  # Example input
    model.add(keras.layers.LSTM(lstm_size_2))
    model.add(keras.layers.PReLU(shared_axes=[1]))  # Apply PReLU to the output of LSTM
    model.add(keras.layers.Dropout(0.2))
    model.add(keras.layers.LayerNormalization())
    model.add(keras.layers.Dense(dense_size))
    model.add(keras.layers.PReLU())
    model.add(keras.layers.Dense(3, activation='softmax'))

    model.compile(
    optimizer='adamW',
    loss=focal_loss(gamma=gamma, alpha=alpha),  # alpha = list of class weights /focal_loss(gamma=0.5, alpha=alpha)
    metrics = ['accuracy']+ [
    tf.keras.metrics.Precision(class_id=1, name='prec_buy'),
    tf.keras.metrics.Recall   (class_id=1, name='rec_buy'),
    tf.keras.metrics.Precision(class_id=2, name='prec_sell'),
    tf.keras.metrics.Recall   (class_id=2, name='rec_sell')
]
)
    return model

def build_model_DNN(input_shape,dense1,dense2, gamma, alpha):


# 🧠 1. LSTM Block (no CNN)
    model_DNN = keras.Sequential()
    model_DNN.add(keras.layers.Flatten(input_shape=(input_shape)))  # <- add this X_balanced.shape[2]
    model_DNN.add(keras.layers.Dense(dense1, activation='relu'))
    model_DNN.add(keras.layers.Dropout(0.3))
    model_DNN.add(keras.layers.PReLU())
    model_DNN.add(keras.layers.Dropout(0.3))
    model_DNN.add(keras.layers.PReLU())
    model_DNN.add(keras.layers.Dropout(0.3))
    model_DNN.add(keras.layers.BatchNormalization())
    model_DNN.add(keras.layers.Dense(dense2, activation='relu'))
    model_DNN.add(keras.layers.Dropout(0.3))
    model_DNN.add(keras.layers.Dense(3, activation='softmax'))

    model_DNN.compile(
    optimizer='adamW',
    loss=focal_loss(gamma=gamma, alpha=alpha),  # alpha = list of class weights /focal_loss(gamma=0.5, alpha=alpha)
    metrics = ['accuracy']+ [
    tf.keras.metrics.Precision(class_id=1, name='prec_buy'),
    tf.keras.metrics.Recall   (class_id=1, name='rec_buy'),
    tf.keras.metrics.Precision(class_id=2, name='prec_sell'),
    tf.keras.metrics.Recall   (class_id=2, name='rec_sell')
]
)
    return model_DNN

def create_model(model_id: int):
    if model_id not in best_params or model_id not in model_paths:
        raise ValueError(f"Unknown model_id {model_id}. Choose from {list(best_params)}")

    params = best_params[model_id]
    alpha  = [params['class_0'], params['class_1'], params['class_2']]

    model = load_model(
        model_paths[model_id],
        custom_objects={"focal_loss_fixed": focal_loss(gamma=params['gamma'], alpha=alpha)},
        compile=False
    )
    return model

def test_trai_split(df,thresh):
  len_index = int(len(df)*thresh)
  train = df[:len_index]
  test = df[len_index:]
  return train,test

"""## 9. Hyper‑parameter tuning with Optuna

This section defines the **Optuna objective function** used to search over:

- focal‑loss parameters (class weights and gamma)
- selected model hyper‑parameters.

For each trial, the objective:
1. builds a model using the proposed hyper‑parameters,
2. trains it on the training data,
3. evaluates its performance on validation data
4. returns a score that Optuna seeks to maximise.

"""

def objective(trial):

    # ---------- hyper-parameters to tune ------------------------------------
    alpha = np.array([
        trial.suggest_float("class_0", 1/0.99, 1/0.10),
        trial.suggest_float("class_1", 1/0.10, 1/0.01),
        trial.suggest_float("class_2", 1/0.10, 1/0.01)
    ], dtype="float32")
    alpha /= alpha.sum()                              # normalise so Σα = 1

    gamma = trial.suggest_float("gamma", 0.3, 3.0)
    dense1 = trial.suggest_int("dense1", 32, 64,128)
    dense2 = trial.suggest_int("dense2",16, 32, 64)
    batch_sz = trial.suggest_int('batch_sz', 64, 128)


    # ---------- model, callbacks, fit ---------------------------------------
    model = build_model_DNN(X_balanced.shape[1:],dense1,dense2, gamma, alpha)

    model.compile(
        optimizer='adamw',
        loss=focal_loss(gamma=gamma, alpha=alpha),
        metrics=['accuracy', Precision(), Recall()]
    )

    # --- Training Callbacks ---
    callbacks = [
    # stop when validation BUY precision stops improving
    tf.keras.callbacks.EarlyStopping(
        monitor="val_prec_buy",mode='max', patience=30, restore_best_weights=True),
    tf.keras.callbacks.EarlyStopping(
        monitor="val_prec_sell",mode='max', patience=30, restore_best_weights=True),

    # shrink LR when validation BUY precision plateaus
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_prec_buy",mode='max', patience=15, factor=0.1, min_lr=1e-8),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_prec_sell",mode='max', patience=15, factor=0.1, min_lr=1e-8)


]

    model.fit(
        X_balanced, y_cat_train,
        validation_data=(X_val_seq, y_cat_val),
        epochs=200,
        batch_size=batch_sz,
        verbose=0,
        callbacks=callbacks
    )

    # ---------- validation-set back-test ------------------------------------
    #signals = np.array([decode_with_threshold(p, tau=0.60) for p in model.predict(X_val_seq)])


    y_pred_probs = model.predict(X_val_seq)
    y_pred = np.argmax(y_pred_probs, axis=1)  # Convert softmax outputs to class labels

    decoded_sig = decode_signals(y_pred)

    # last ‘window_size’ rows are lost when we built the sequences
    seq_index   = X_val.index[-len(decoded_sig):]

    val_df   = pd.DataFrame({"signal": decoded_sig}, index=seq_index)
    market   = new_Data.loc[seq_index].drop(columns="signal", errors="ignore")

    merged   = pd.concat([market, val_df], axis=1)
    merged["signal"] = filter_signals(merged["signal"], trad_num=1)

    perf     = simulate_strategy_with_borrow_and_evolution(
        merged, signal_col="signal", price_col="Close"
    )
    equity   = perf["total_equity"]
    max_dd   = (equity / equity.cummax() - 1).min()

    # ---------- save the model & trial attrs --------------------------------
    model_path = f"/content/drive/MyDrive/train_DNN_optuna_model_trial_{trial.number}.keras"
    model.save(model_path, overwrite=True)

    trial.set_user_attr("model_path", model_path)
    trial.set_user_attr("gamma", gamma)
    trial.set_user_attr("alpha", alpha.tolist())

    # Optuna minimises the returned value
    return max_dd if max_dd < 0 else -1

"""## 10. Data pre‑processing for modeling

In this stage we:

- load the cleaned **futures** and **spot** Excel files from Google Drive
- generate and filter trading signals
- build a tabular dataset that combines prices, indicators and labels
- drop non‑numeric columns and select the final feature set
- apply rolling standardisation to the features
- create train / validation / test splits and sequence them for DNN and LSTM.

After this block, the data is ready to be fed into the deep learning models.

"""

Futures_spot_price = pd.read_excel('/content/drive/MyDrive/data_futures_sb11_updated.xlsx')
Futures_spot_price = clean_SB11(Futures_spot_price)

Spot_Price = pd.read_excel('/content/drive/MyDrive/data_spot_VHP_updated.xlsx')

Spot_Price = clean_spot(Spot_Price)

Data_spot_Strategy_filtered= generate_signals(Spot_Price,Futures_spot_price,vol_window_fut=10,trend_fut=10,vol_window=10,trend_window=10,RSIwindow=15,Zscorewindow=30,
                                                      k=5 ,vote_thresh=0, weighted=True,
                               window_slope=10, RSI_thresh_up=60, RSI_thresh_down=40, slope_thresh=1,order = 5)

result_df_spot_alter_buy_sell = simulate_strategy_with_borrow_and_evolution(Data_spot_Strategy_filtered, signal_col='signal', price_col='Close')

benchmark = compute_buy_and_hold(Data_spot_Strategy_filtered.tail(len(result_df_spot_alter_buy_sell['total_equity'])), initial_cash=100000)

"""### Visual check of the target strategy

The following plot shows:

- the underlying price series,
- BUY / SELL / HOLD signals generated by the rule‑based strategy, and
- the resulting equity curve compared to buy‑and‑hold.

This visualisation is the **reference behaviour** that our deep learning models
will try to approximate by learning from the synthetic labels created earlier.

"""

plot_interactive_signals_and_equity(Data_spot_Strategy_filtered,result_df_spot_alter_buy_sell,benchmark)

new_Data=Data_spot_Strategy_filtered.copy()

new_Data = droping_non_num(new_Data)

features = ['MID','Close_shifted', 'MID_shifted_1',
       'MID_shifted_2', 'Vol_fut', 'Trend_fut', 'Volatility', 'Trend', 'RSI',
       'Zscore', 'ATR_mid', 'SMA_15', 'SMA_30', 'EMA_15', 'EMA_30',
       'slopeMA15', 'slopeMA30', 'RSI_slope']

X_scaled,y_scaled= rolling_standard_scaling(new_Data ,features,30)

window_size =60

X_raw, X_test_raw = test_trai_split(X_scaled, 0.8)
y_raw, y_test_raw = test_trai_split(y_scaled, 0.8)
X_train,X_val = test_trai_split(X_raw, 0.8)
y_train,y_val = test_trai_split(y_raw, 0.8)

X_balanced, y_balanced,index= create_lstm_sequences(X_train, y_train,window_size)
X_val_seq,y_val_seq,index = create_lstm_sequences(X_val, y_val, window_size)
X_test,y_test,index = create_lstm_sequences(X_test_raw, y_test_raw, window_size)

y_cat_val = to_categorical(y_val_seq, num_classes=3)
y_cat_train = to_categorical(y_balanced, num_classes=3)

"""## 11. Fine‑tuning via Optuna study

We now launch an **Optuna study** to explore different hyper‑parameter
configurations. For each trial, the objective function defined above is called,
and Optuna keeps track of the best‑performing parameter set.

The outcome of this section is:
- the best hyper‑parameters found, and
- a record of all trials that can be inspected or reused later.

"""

#initial_params = {'class_0': 0.37420780987378677, 'class_1': 3.1006880863229322, 'class_2': 9.234505519513846, 'gamma': 1.9544534290063922}
study = optuna.create_study(direction='maximize')  # or 'minimize'
#study.enqueue_trial(initial_params)
#study.optimize(lambda trial: objective(trial), n_trials=60)
study.optimize(objective, n_trials=100)

print("Best params:", study.best_params)
print("Best score:", study.best_value)
optuna.visualization.plot_optimization_history(study).show()

qualified_trials = [trial for trial in study.trials if trial.value >= -0.25]

print(f"Found {len(qualified_trials)} trials with score >= -16")

for trial in qualified_trials:
    print(f"\n🎯 Trial {trial.number} - Score: {trial.value:.4f}")

    try:
        model_path = trial.user_attrs.get("model_path")
        gamma = trial.user_attrs.get("gamma")
        alpha = np.array(trial.user_attrs.get("alpha"), dtype=np.float32)

        if model_path and gamma is not None and alpha is not None:
            model = load_model(model_path, custom_objects={"focal_loss_fixed": focal_loss(gamma=gamma, alpha=alpha)})

            # Predict
            y_pred_probs = model.predict(X_test)
            y_pred = np.argmax(y_pred_probs, axis=1)
            signals = np.array([decode_with_threshold(p, tau=0.45) for p in y_pred_probs])
            decoded_test = decode_signals(y_pred )
            test_idx = X_test_raw.index[-len(decoded_test):]
            test_df = pd.DataFrame({'signal': decoded_test}, index=test_idx)
            test_slice = new_Data.loc[test_idx].drop(columns="signal", errors="ignore")
            merged = pd.concat([test_slice, test_df], axis=1)
            merged = merged.drop(columns=['Close'], errors='ignore')
            merged["signal"] = filter_signals(merged["signal"], trad_num=1)
            Data = pd.merge(merged, Futures_spot_price[['Close']], on='Date', how='inner')
            perf_test = simulate_strategy_with_borrow_and_evolution(
              Data, signal_col="signal", price_col="Close")
            benchmark = compute_buy_and_hold(Data.tail(len(perf_test['total_equity'])), initial_cash=100000)
            plot_interactive_signals_and_equity(Data,perf_test,benchmark)

    except Exception as e:
        print(f"Error processing trial {trial.number}: {e}")

"""## 12. Backtesting the selected model(s)

Finally, we backtest the deep learning models using the prepared test data:

- load one or more trained models by ID
- run them on the scaled feature set
- reconstruct trading signals from the model predictions
- plot performance over the chosen evaluation periods.

This section allows you to assess whether the learned models generalise well
out‑of‑sample compared to the original rule‑based strategy.

"""

# ------------------------ hyper-parameter dictionaries ------------------------
best_params = {
    #22: {'class_0': 1.7880886155848588, 'class_1': 60.80659083965935, 'class_2': 84.87239395263839, 'gamma': 0.8571881591463033},

    #38: {'class_0': 0.2523354753039283, 'class_1': 5.251306378812071,'class_2': 7.527256210446432,  'gamma'  : 1.0078147555492118},

     #4: {'class_0': 0.18384372306305424, 'class_1': 10.020804654865522,'class_2': 7.507627228283542,   'gamma'  : 0.5103190576815031},
    49:{'class_0': 9.657570994463043, 'class_1': 68.58487680396186, 'class_2': 60.7332759161441, 'gamma': 0.9451370443566887},
    43 : {'class_0': 2.0198398634747714, 'class_1': 86.65131524811406, 'class_2': 60.69795233453225, 'gamma': 0.8070834133323191, 'lstm_size': 32, 'dense_size': 16},
    94 : {'class_0': 1.9095783160087472, 'class_1': 87.30190110293127, 'class_2': 71.87333446511941, 'gamma': 0.6628679495819036, 'lstm_size': 32, 'dense_size': 16},
    95 : {'class_0': 1.9095783160087472, 'class_1': 87.30190110293127, 'class_2': 71.87333446511941, 'gamma': 0.6628679495819036, 'lstm_size': 32, 'dense_size': 16}
}

# --------------------------- saved-model file paths ---------------------------
model_paths = {
    #22: "/content/drive/MyDrive/train_3_optuna_model_trial_22.keras",
    #38: "/content/drive/MyDrive/optuna_model_trial_38.keras",
     #4: "/content/drive/MyDrive/optuna_model_trial_4.keras",
    49 :"/content/drive/MyDrive/train_DNN_optuna_model_trial_49.keras",
    43: "/content/drive/MyDrive/train_DNN_optuna_model_trial_43.keras",
    94: "/content/drive/MyDrive/train_DNN_optuna_model_trial_94.keras",
    95: "/content/drive/MyDrive/train_LSTM_optuna_model_trial_95.keras"

}

nums = [43]

scaled_df_test = pd.concat([X_scaled,y_scaled],axis = 1)

plot_models_results(scaled_df_test,'2023-5-7',"2025-07-10",nums)

plot_models_results(scaled_df_test,'2015-4-15',"2025-07-10"nums)